import { query } from "../pool";

export interface PairingTokenRow {
  id: string;
  pair_id: string;
  token: string;
  slug: string;
  code: string;
  method: string;
  created_by: string;
  expires_at: string;
  used_by: string | null;
  used_at: string | null;
  revoked_at: string | null;
  created_at: string;
}

export interface CreatePairingTokenData {
  pair_id: string;
  slug: string;
  code: string;
  method: string;
  created_by: string;
  expires_at: Date;
}

/**
 * Insert a new pairing token row.
 * The token UUID is generated by the database (DEFAULT gen_random_uuid()).
 */
export async function createPairingToken(
  data: CreatePairingTokenData,
): Promise<PairingTokenRow> {
  const result = await query<PairingTokenRow>(
    `INSERT INTO pairing_tokens (pair_id, slug, code, method, created_by, expires_at)
     VALUES ($1, $2, $3, $4, $5, $6)
     RETURNING *`,
    [data.pair_id, data.slug, data.code, data.method, data.created_by, data.expires_at],
  );
  return result.rows[0];
}

/**
 * Find an active (unused, non-revoked, non-expired) pairing token by its UUID token.
 */
export async function findByToken(token: string): Promise<PairingTokenRow | null> {
  const result = await query<PairingTokenRow>(
    `SELECT * FROM pairing_tokens
     WHERE token = $1
       AND used_at IS NULL
       AND revoked_at IS NULL
       AND expires_at > NOW()`,
    [token],
  );
  return result.rows[0] ?? null;
}

/**
 * Find an active (unused, non-revoked, non-expired) pairing token by its slug (invite link).
 */
export async function findBySlug(slug: string): Promise<PairingTokenRow | null> {
  const result = await query<PairingTokenRow>(
    `SELECT * FROM pairing_tokens
     WHERE slug = $1
       AND used_at IS NULL
       AND revoked_at IS NULL
       AND expires_at > NOW()`,
    [slug],
  );
  return result.rows[0] ?? null;
}

/**
 * Find an active (unused, non-revoked, non-expired) pairing token by its code (case-insensitive).
 */
export async function findByCode(code: string): Promise<PairingTokenRow | null> {
  const result = await query<PairingTokenRow>(
    `SELECT * FROM pairing_tokens
     WHERE UPPER(code) = UPPER($1)
       AND used_at IS NULL
       AND revoked_at IS NULL
       AND expires_at > NOW()`,
    [code],
  );
  return result.rows[0] ?? null;
}

/**
 * Mark a pairing token as used by a specific user.
 */
export async function markUsed(id: string, usedBy: string): Promise<PairingTokenRow> {
  const result = await query<PairingTokenRow>(
    `UPDATE pairing_tokens
     SET used_by = $2, used_at = NOW()
     WHERE id = $1
     RETURNING *`,
    [id, usedBy],
  );
  if (!result.rows[0]) {
    throw new Error(`Pairing token ${id} not found`);
  }
  return result.rows[0];
}

/**
 * Revoke all active (unused, non-revoked) pairing tokens for a given pair.
 */
export async function revokeByPairId(pairId: string): Promise<void> {
  await query(
    `UPDATE pairing_tokens
     SET revoked_at = NOW()
     WHERE pair_id = $1
       AND used_at IS NULL
       AND revoked_at IS NULL`,
    [pairId],
  );
}
