-- ============================================================================
-- JibJib Database Schema — PostgreSQL 16
-- Version: 1.0 (MVP)
-- Last Updated: February 2026
--
-- Usage:
--   psql -U jibjib -d jibjib -f jibjib-database-schema.sql
--
-- Notes:
--   - All IDs are UUID v4 (generated by app or gen_random_uuid())
--   - Timestamps are UTC (timestamptz)
--   - Soft deletes use deleted_at (NULL = active)
--   - JSONB used for flexible fields (photo_urls, sync payload)
--   - Indexes optimized for real-time list queries
-- ============================================================================

-- ────────────────────────────────────────────────────────────────────────────
-- EXTENSIONS
-- ────────────────────────────────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";      -- uuid_generate_v4()
CREATE EXTENSION IF NOT EXISTS "pgcrypto";        -- gen_random_uuid() (preferred)

-- ────────────────────────────────────────────────────────────────────────────
-- ENUMS
-- ────────────────────────────────────────────────────────────────────────────
CREATE TYPE user_language AS ENUM ('en', 'fr', 'ar');
CREATE TYPE auth_provider AS ENUM ('google', 'apple', 'facebook', 'anonymous');
CREATE TYPE pair_status AS ENUM ('active', 'archived');
CREATE TYPE pairing_method AS ENUM ('qr', 'invite_link', 'code', 'all');
CREATE TYPE item_category AS ENUM (
  'produce', 'dairy', 'meat', 'seafood', 'bakery', 'frozen',
  'canned', 'snacks', 'beverages', 'household', 'personal_care',
  'baby', 'pet', 'other'
);
CREATE TYPE trip_status AS ENUM ('active', 'completed', 'auto_ended');
CREATE TYPE sync_operation AS ENUM ('add', 'edit', 'delete', 'check', 'uncheck');
CREATE TYPE sync_entity AS ENUM ('item', 'message', 'list', 'trip');
CREATE TYPE message_type AS ENUM ('text', 'sticker', 'system');
CREATE TYPE notification_type AS ENUM (
  'items_added', 'item_edited', 'trip_started', 'item_message',
  'voice_note', 'trip_completed', 'last_minute_add', 'pairing_invite'
);

-- ────────────────────────────────────────────────────────────────────────────
-- USERS
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE users (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name            VARCHAR(100) NOT NULL,
  avatar_url      TEXT,                            -- Minio URL or NULL for initial-based avatar
  language        user_language NOT NULL DEFAULT 'en',
  auth_provider   auth_provider NOT NULL DEFAULT 'anonymous',
  auth_id         VARCHAR(255),                    -- Provider-specific ID (Google sub, Apple sub, etc.)
  onesignal_player_id VARCHAR(255),                -- OneSignal device token
  device_os       VARCHAR(20),                     -- 'ios' or 'android'
  app_version     VARCHAR(20),                     -- e.g., '1.0.0'
  timezone        VARCHAR(50) DEFAULT 'UTC',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_active_at  TIMESTAMPTZ,

  CONSTRAINT uq_auth UNIQUE (auth_provider, auth_id)
);

CREATE INDEX idx_users_onesignal ON users (onesignal_player_id) WHERE onesignal_player_id IS NOT NULL;
CREATE INDEX idx_users_last_active ON users (last_active_at);

-- ────────────────────────────────────────────────────────────────────────────
-- PAIRS
-- Represents a pairing between two users. One active pair per user.
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE pairs (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_a_id       UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  user_b_id       UUID REFERENCES users(id) ON DELETE SET NULL,  -- NULL until User B joins
  status          pair_status NOT NULL DEFAULT 'active',
  paired_at       TIMESTAMPTZ,                     -- Set when User B joins
  archived_at     TIMESTAMPTZ,                     -- Set on unpair
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT chk_different_users CHECK (user_a_id != user_b_id)
);

CREATE INDEX idx_pairs_user_a ON pairs (user_a_id, status);
CREATE INDEX idx_pairs_user_b ON pairs (user_b_id, status) WHERE user_b_id IS NOT NULL;
CREATE INDEX idx_pairs_active ON pairs (status) WHERE status = 'active';

-- Ensure each user has at most one active pair
CREATE UNIQUE INDEX uq_user_a_active ON pairs (user_a_id) WHERE status = 'active';
CREATE UNIQUE INDEX uq_user_b_active ON pairs (user_b_id) WHERE status = 'active' AND user_b_id IS NOT NULL;

-- ────────────────────────────────────────────────────────────────────────────
-- PAIRING TOKENS
-- Supports QR, invite link, and manual code. All single-use, time-limited.
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE pairing_tokens (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  pair_id         UUID NOT NULL REFERENCES pairs(id) ON DELETE CASCADE,
  token           UUID NOT NULL DEFAULT gen_random_uuid(),  -- For link: jibjib.shop/pair/{slug}
  slug            VARCHAR(8) NOT NULL,              -- Short URL slug (e.g., 'X7k9mQ')
  code            VARCHAR(7) NOT NULL,              -- Manual code (e.g., 'JIB-X7K')
  method          pairing_method NOT NULL,
  created_by      UUID NOT NULL REFERENCES users(id),
  expires_at      TIMESTAMPTZ NOT NULL,
  used_by         UUID REFERENCES users(id),
  used_at         TIMESTAMPTZ,
  revoked_at      TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT uq_token UNIQUE (token),
  CONSTRAINT uq_slug UNIQUE (slug),
  CONSTRAINT uq_code_active UNIQUE (code)          -- Codes are unique while active
);

CREATE INDEX idx_pairing_slug ON pairing_tokens (slug) WHERE used_at IS NULL AND revoked_at IS NULL;
CREATE INDEX idx_pairing_code ON pairing_tokens (code) WHERE used_at IS NULL AND revoked_at IS NULL;
CREATE INDEX idx_pairing_expires ON pairing_tokens (expires_at) WHERE used_at IS NULL;

-- ────────────────────────────────────────────────────────────────────────────
-- LISTS
-- One active list per pair in MVP. Multiple lists in v1.1.
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE lists (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  pair_id         UUID NOT NULL REFERENCES pairs(id) ON DELETE CASCADE,
  name            VARCHAR(100) NOT NULL DEFAULT 'Grocery',
  is_active       BOOLEAN NOT NULL DEFAULT TRUE,
  is_archived     BOOLEAN NOT NULL DEFAULT FALSE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_lists_pair ON lists (pair_id, is_active);

-- ────────────────────────────────────────────────────────────────────────────
-- ITEMS
-- Core entity. Belongs to a list. Supports soft delete, photos, voice.
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE items (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  list_id         UUID NOT NULL REFERENCES lists(id) ON DELETE CASCADE,
  name            VARCHAR(255) NOT NULL,
  category        item_category NOT NULL DEFAULT 'other',
  quantity        VARCHAR(50),                      -- Freeform: "2x", "500g", "1 bunch"
  is_checked      BOOLEAN NOT NULL DEFAULT FALSE,
  checked_by      UUID REFERENCES users(id),
  checked_at      TIMESTAMPTZ,
  position        INTEGER NOT NULL DEFAULT 0,       -- Sort order within category
  photo_urls      JSONB DEFAULT '[]'::jsonb,        -- Array of Minio URLs, max 3
  voice_url       TEXT,                             -- Single Minio URL
  created_by      UUID NOT NULL REFERENCES users(id),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at      TIMESTAMPTZ,                      -- Soft delete

  CONSTRAINT chk_photo_limit CHECK (jsonb_array_length(photo_urls) <= 3)
);

CREATE INDEX idx_items_list ON items (list_id, deleted_at) WHERE deleted_at IS NULL;
CREATE INDEX idx_items_list_category ON items (list_id, category, position) WHERE deleted_at IS NULL;
CREATE INDEX idx_items_checked ON items (list_id, is_checked) WHERE deleted_at IS NULL;
CREATE INDEX idx_items_created_at ON items (list_id, created_at DESC) WHERE deleted_at IS NULL;

-- ────────────────────────────────────────────────────────────────────────────
-- MESSAGES
-- Per-item chat thread. Each message belongs to one item.
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE messages (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  item_id         UUID NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  sender_id       UUID NOT NULL REFERENCES users(id),
  text            TEXT NOT NULL,
  type            message_type NOT NULL DEFAULT 'text',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_messages_item ON messages (item_id, created_at ASC);
CREATE INDEX idx_messages_sender ON messages (sender_id, created_at DESC);

-- ────────────────────────────────────────────────────────────────────────────
-- TRIPS
-- Shopping trip lifecycle. One active trip per list at a time.
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE trips (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  list_id         UUID NOT NULL REFERENCES lists(id) ON DELETE CASCADE,
  shopper_id      UUID NOT NULL REFERENCES users(id),
  status          trip_status NOT NULL DEFAULT 'active',
  items_total     INTEGER NOT NULL DEFAULT 0,
  items_done      INTEGER NOT NULL DEFAULT 0,
  items_added_during INTEGER NOT NULL DEFAULT 0,    -- Items added after trip started
  started_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ended_at        TIMESTAMPTZ,
  
  CONSTRAINT chk_items CHECK (items_done <= items_total + items_added_during)
);

CREATE INDEX idx_trips_list ON trips (list_id, status);
CREATE INDEX idx_trips_active ON trips (list_id) WHERE status = 'active';
CREATE INDEX idx_trips_shopper ON trips (shopper_id, started_at DESC);

-- Ensure only one active trip per list
CREATE UNIQUE INDEX uq_active_trip ON trips (list_id) WHERE status = 'active';

-- ────────────────────────────────────────────────────────────────────────────
-- SYNC QUEUE
-- Offline changes queued for sync. Processed FIFO per device.
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE sync_queue (
  id              BIGSERIAL PRIMARY KEY,            -- Sequential for ordering
  user_id         UUID NOT NULL REFERENCES users(id),
  device_id       VARCHAR(100) NOT NULL,            -- Unique device identifier
  operation       sync_operation NOT NULL,
  entity_type     sync_entity NOT NULL,
  entity_id       UUID NOT NULL,                    -- ID of the item/message/etc
  payload         JSONB NOT NULL,                   -- Full change data
  client_timestamp TIMESTAMPTZ NOT NULL,            -- When change happened on device
  server_timestamp TIMESTAMPTZ DEFAULT NOW(),       -- When server received it
  synced_at       TIMESTAMPTZ,                      -- When sync confirmed to device
  conflict        BOOLEAN DEFAULT FALSE,            -- Flagged if conflict detected
  conflict_data   JSONB                             -- Other version if conflict
);

CREATE INDEX idx_sync_user_device ON sync_queue (user_id, device_id, synced_at) WHERE synced_at IS NULL;
CREATE INDEX idx_sync_entity ON sync_queue (entity_type, entity_id, client_timestamp);
CREATE INDEX idx_sync_unsynced ON sync_queue (user_id, id ASC) WHERE synced_at IS NULL;

-- ────────────────────────────────────────────────────────────────────────────
-- ITEM HISTORY
-- Aggregated purchase patterns per pair. Powers v2.0 smart suggestions.
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE item_history (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  pair_id         UUID NOT NULL REFERENCES pairs(id) ON DELETE CASCADE,
  item_name       VARCHAR(255) NOT NULL,            -- Normalized lowercase
  category        item_category NOT NULL DEFAULT 'other',
  last_added_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  add_count       INTEGER NOT NULL DEFAULT 1,
  avg_interval_days REAL,                           -- Average days between purchases
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT uq_pair_item UNIQUE (pair_id, item_name)
);

CREATE INDEX idx_history_pair ON item_history (pair_id, add_count DESC);
CREATE INDEX idx_history_frequency ON item_history (pair_id, avg_interval_days) WHERE avg_interval_days IS NOT NULL;

-- ────────────────────────────────────────────────────────────────────────────
-- NOTIFICATION PREFERENCES
-- Per-user, per-type toggle for push notifications.
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE notification_preferences (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  notification_type notification_type NOT NULL,
  enabled         BOOLEAN NOT NULL DEFAULT TRUE,
  
  CONSTRAINT uq_user_notif UNIQUE (user_id, notification_type)
);

CREATE INDEX idx_notif_prefs_user ON notification_preferences (user_id);

-- ────────────────────────────────────────────────────────────────────────────
-- SESSIONS (Refresh Tokens)
-- JWT refresh token tracking for rotation and revocation.
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE sessions (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  refresh_token   VARCHAR(500) NOT NULL,
  device_id       VARCHAR(100) NOT NULL,
  device_name     VARCHAR(100),
  expires_at      TIMESTAMPTZ NOT NULL,
  revoked_at      TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  
  CONSTRAINT uq_refresh UNIQUE (refresh_token)
);

CREATE INDEX idx_sessions_user ON sessions (user_id, revoked_at) WHERE revoked_at IS NULL;
CREATE INDEX idx_sessions_token ON sessions (refresh_token) WHERE revoked_at IS NULL;
CREATE INDEX idx_sessions_expires ON sessions (expires_at);

-- ────────────────────────────────────────────────────────────────────────────
-- SUPPORT TICKETS (Telegram Bot)
-- Tracks support conversations initiated via Telegram bot.
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE support_tickets (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id         UUID REFERENCES users(id),        -- NULL if user not identified
  telegram_chat_id BIGINT NOT NULL,
  device_info     JSONB,                            -- OS, version, language, etc.
  status          VARCHAR(20) NOT NULL DEFAULT 'open',  -- open, resolved, closed
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  resolved_at     TIMESTAMPTZ
);

CREATE INDEX idx_support_status ON support_tickets (status, created_at DESC);

-- ────────────────────────────────────────────────────────────────────────────
-- FUNCTIONS
-- ────────────────────────────────────────────────────────────────────────────

-- Auto-update updated_at on row modification
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_lists_updated_at BEFORE UPDATE ON lists FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_items_updated_at BEFORE UPDATE ON items FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER trg_item_history_updated_at BEFORE UPDATE ON item_history FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- Update item_history on item creation (for smart suggestions in v2.0)
CREATE OR REPLACE FUNCTION update_item_history()
RETURNS TRIGGER AS $$
DECLARE
  v_pair_id UUID;
  v_normalized_name VARCHAR(255);
BEGIN
  -- Get pair_id from list
  SELECT l.pair_id INTO v_pair_id FROM lists l WHERE l.id = NEW.list_id;
  v_normalized_name := LOWER(TRIM(NEW.name));
  
  INSERT INTO item_history (pair_id, item_name, category, last_added_at, add_count)
  VALUES (v_pair_id, v_normalized_name, NEW.category, NOW(), 1)
  ON CONFLICT (pair_id, item_name) DO UPDATE SET
    category = NEW.category,
    add_count = item_history.add_count + 1,
    avg_interval_days = EXTRACT(EPOCH FROM (NOW() - item_history.last_added_at)) / 86400.0,
    last_added_at = NOW(),
    updated_at = NOW();
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_item_history AFTER INSERT ON items FOR EACH ROW EXECUTE FUNCTION update_item_history();

-- ────────────────────────────────────────────────────────────────────────────
-- SEED DATA — Default notification preferences for new users
-- ────────────────────────────────────────────────────────────────────────────

-- Function to seed notification prefs on user creation
CREATE OR REPLACE FUNCTION seed_notification_preferences()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO notification_preferences (user_id, notification_type, enabled)
  SELECT NEW.id, t.type, TRUE
  FROM unnest(enum_range(NULL::notification_type)) AS t(type);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_seed_notif_prefs AFTER INSERT ON users FOR EACH ROW EXECUTE FUNCTION seed_notification_preferences();

-- ────────────────────────────────────────────────────────────────────────────
-- SEED DATA — Common grocery items for autocomplete
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE common_items (
  id              SERIAL PRIMARY KEY,
  name_en         VARCHAR(100) NOT NULL,
  name_fr         VARCHAR(100),
  name_ar         VARCHAR(100),
  category        item_category NOT NULL DEFAULT 'other',
  popularity      INTEGER NOT NULL DEFAULT 0         -- Higher = more common
);

CREATE INDEX idx_common_items_pop ON common_items (popularity DESC);
CREATE INDEX idx_common_items_name ON common_items (name_en);

INSERT INTO common_items (name_en, name_fr, name_ar, category, popularity) VALUES
  -- Produce
  ('Tomatoes', 'Tomates', '\u0637\u0645\u0627\u0637\u0645', 'produce', 95),
  ('Onions', 'Oignons', '\u0628\u0635\u0644', 'produce', 93),
  ('Potatoes', 'Pommes de terre', '\u0628\u0637\u0627\u0637\u0633', 'produce', 92),
  ('Bananas', 'Bananes', '\u0645\u0648\u0632', 'produce', 90),
  ('Apples', 'Pommes', '\u062A\u0641\u0627\u062D', 'produce', 88),
  ('Carrots', 'Carottes', '\u062C\u0632\u0631', 'produce', 85),
  ('Lemons', 'Citrons', '\u0644\u064A\u0645\u0648\u0646', 'produce', 84),
  ('Garlic', 'Ail', '\u062B\u0648\u0645', 'produce', 82),
  ('Lettuce', 'Laitue', '\u062E\u0633', 'produce', 78),
  ('Cucumbers', 'Concombres', '\u062E\u064A\u0627\u0631', 'produce', 76),
  ('Peppers', 'Poivrons', '\u0641\u0644\u0641\u0644', 'produce', 74),
  ('Avocados', 'Avocats', '\u0623\u0641\u0648\u0643\u0627\u062F\u0648', 'produce', 70),

  -- Dairy
  ('Milk', 'Lait', '\u062D\u0644\u064A\u0628', 'dairy', 96),
  ('Eggs', 'Oeufs', '\u0628\u064A\u0636', 'dairy', 94),
  ('Butter', 'Beurre', '\u0632\u0628\u062F\u0629', 'dairy', 88),
  ('Yogurt', 'Yaourt', '\u0632\u0628\u0627\u062F\u064A', 'dairy', 86),
  ('Cheese', 'Fromage', '\u062C\u0628\u0646', 'dairy', 84),
  ('Cream', 'Cr\u00e8me', '\u0642\u0634\u0637\u0629', 'dairy', 72),

  -- Meat
  ('Chicken', 'Poulet', '\u062F\u062C\u0627\u062C', 'meat', 90),
  ('Ground Beef', 'Viande hach\u00e9e', '\u0644\u062D\u0645 \u0645\u0641\u0631\u0648\u0645', 'meat', 85),
  ('Lamb', 'Agneau', '\u0644\u062D\u0645 \u063A\u0646\u0645', 'meat', 72),

  -- Seafood
  ('Fish', 'Poisson', '\u0633\u0645\u0643', 'seafood', 78),

  -- Bakery
  ('Bread', 'Pain', '\u062E\u0628\u0632', 'bakery', 94),
  ('Flour', 'Farine', '\u062F\u0642\u064A\u0642', 'bakery', 80),
  ('Sugar', 'Sucre', '\u0633\u0643\u0631', 'bakery', 78),

  -- Beverages
  ('Water', 'Eau', '\u0645\u0627\u0621', 'beverages', 92),
  ('Juice', 'Jus', '\u0639\u0635\u064A\u0631', 'beverages', 80),
  ('Coffee', 'Caf\u00e9', '\u0642\u0647\u0648\u0629', 'beverages', 82),
  ('Tea', 'Th\u00e9', '\u0634\u0627\u064A', 'beverages', 78),

  -- Household
  ('Dish Soap', 'Liquide vaisselle', '\u0633\u0627\u0626\u0644 \u063A\u0633\u064A\u0644', 'household', 75),
  ('Trash Bags', 'Sacs poubelle', '\u0623\u0643\u064A\u0627\u0633 \u0642\u0645\u0627\u0645\u0629', 'household', 70),
  ('Paper Towels', 'Essuie-tout', '\u0645\u0646\u0627\u062F\u064A\u0644 \u0648\u0631\u0642\u064A\u0629', 'household', 72),
  ('Toilet Paper', 'Papier toilette', '\u0648\u0631\u0642 \u062A\u0648\u0627\u0644\u064A\u062A', 'household', 74),

  -- Snacks
  ('Chips', 'Chips', '\u0634\u064A\u0628\u0633', 'snacks', 72),
  ('Cookies', 'Biscuits', '\u0628\u0633\u0643\u0648\u064A\u062A', 'snacks', 70),
  ('Chocolate', 'Chocolat', '\u0634\u0648\u0643\u0648\u0644\u0627\u062A\u0629', 'snacks', 74),
  ('Nuts', 'Noix', '\u0645\u0643\u0633\u0631\u0627\u062A', 'snacks', 68),

  -- Frozen
  ('Ice Cream', 'Glace', '\u0622\u064A\u0633 \u0643\u0631\u064A\u0645', 'frozen', 70),
  ('Frozen Vegetables', 'L\u00e9gumes surgel\u00e9s', '\u062E\u0636\u0631\u0648\u0627\u062A \u0645\u062C\u0645\u062F\u0629', 'frozen', 65),

  -- Staples
  ('Rice', 'Riz', '\u0623\u0631\u0632', 'other', 88),
  ('Pasta', 'P\u00e2tes', '\u0645\u0639\u0643\u0631\u0648\u0646\u0629', 'other', 85),
  ('Olive Oil', 'Huile d''olive', '\u0632\u064A\u062A \u0632\u064A\u062A\u0648\u0646', 'other', 86),
  ('Salt', 'Sel', '\u0645\u0644\u062D', 'other', 80),
  ('Pepper', 'Poivre', '\u0641\u0644\u0641\u0644 \u0623\u0633\u0648\u062F', 'other', 75),
  ('Canned Tomatoes', 'Tomates en conserve', '\u0637\u0645\u0627\u0637\u0645 \u0645\u0639\u0644\u0628\u0629', 'other', 74),
  ('Honey', 'Miel', '\u0639\u0633\u0644', 'other', 70);

-- ────────────────────────────────────────────────────────────────────────────
-- CLEANUP JOBS (to be run via cron or pg_cron)
-- ────────────────────────────────────────────────────────────────────────────

-- Delete expired, unused pairing tokens (run hourly)
-- DELETE FROM pairing_tokens WHERE expires_at < NOW() AND used_at IS NULL;

-- Hard-delete soft-deleted items older than 30 days (run daily)
-- DELETE FROM items WHERE deleted_at IS NOT NULL AND deleted_at < NOW() - INTERVAL '30 days';

-- Archive pairs inactive for 90 days (run weekly)
-- UPDATE pairs SET status = 'archived', archived_at = NOW()
-- WHERE status = 'active'
-- AND NOT EXISTS (
--   SELECT 1 FROM items i
--   JOIN lists l ON l.id = i.list_id
--   WHERE l.pair_id = pairs.id AND i.updated_at > NOW() - INTERVAL '90 days'
-- );

-- Purge synced queue entries older than 7 days (run daily)
-- DELETE FROM sync_queue WHERE synced_at IS NOT NULL AND synced_at < NOW() - INTERVAL '7 days';
